FROM alpine:3.15

WORKDIR /gerbera_build
COPY . .

RUN apk add --no-cache tini \
        util-linux sqlite-libs mariadb-connector-c zlib \
        file libexif curl ffmpeg ffmpegthumbnailer \
        libmatroska libebml taglib && \
    apk add --no-cache --virtual .dev-packages gcc g++ pkgconf make automake autoconf libtool \
	    util-linux-dev sqlite-dev mariadb-connector-c-dev cmake zlib-dev \
	    file-dev libexif-dev curl-dev ffmpeg-dev ffmpegthumbnailer-dev wget xz \
	    libmatroska-dev libebml-dev taglib-dev git bash && \
    git clone https://github.com/gerbera/gerbera.git -b v1.11.0 && \
    mkdir build && \
    cd build && \
    sh ../gerbera/scripts/install-pugixml.sh && \
    sh ../gerbera/scripts/install-pupnp.sh && \
    sh ../gerbera/scripts/install-duktape.sh && \
    sh ../gerbera/scripts/install-fmt.sh && \
    sh ../gerbera/scripts/install-spdlog.sh && \
    cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 \
        -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 \
        -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=0 -DWITH_DEBUG=1 -DWITH_INOTIFY=1 && \
    make -j`nproc` && \
    make install && \
    rm -rf /gerbera_build && \
    apk del --purge .dev-packages

EXPOSE 49152
EXPOSE 1900/udp

ENTRYPOINT ["/sbin/tini", "--"]
CMD [ "gerbera","-p", "49152" ]
