version: "3.8"
services:
  gerbera:
    build: ./gerbera
    volumes:
      - ./gerbera/config:/root/.config/gerbera
      - /srv/movie:/srv/movie:ro
      - /srv/movie_kana:/srv/movie_kana:ro
    network_mode: host
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10M"
