services:
  gerbera:
    build:
      context: ./gerbera
      dockerfile: Dockerfile
      args:
        GERBERA_VERSION: "v2.4.1"
    volumes:
      - ./gerbera/config:/root/.config/gerbera
      - ./gerbera/scripts:/root/.config/scripts
      - /srv/movie2:/srv/movie2:ro
      - /srv/movie_recorded:/srv/movie_recorded:ro
    network_mode: host
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10M"
